updated varaiables templates

diff --git a/14-installtioncheck b/14-installtioncheck
--- a/14-installtioncheck
+++ b/14-installtioncheck
@@ -1,36 +1,77 @@
+# #!/bin/bash
+
+# USERID=$(id -u)
+
+# if [ "$USERID" -ne 0 ]; then 
+#     echo "Only root users can execute this script"
+#     exit 1
+# fi
+
+# validation(){
+#     if [ $1 -ne 0 ]; then 
+#         echo "$2 is failed"
+#         exit 1
+#     else 
+#         echo "$2 is completed"
+#     fi
+# }
+
+# checksoft(){
+#     if dnf list installed $1 &> /dev/null; then 
+#         echo "$1 already installed"
+#         exit 1
+#     else
+#         echo "Installing $1"
+#         dnf install $1 -y
+#     fi
+# }
+
+# checksoft nginx
+# validation $? "nginx installation"
+
+# checksoft mysql
+# validation $? "mysql installation"
+
+# checksoft nodejs
+# validation $? "nodejs installation"
+
+
 #!/bin/bash
 
 USERID=$(id -u)
 
-if [ "$USERID" -ne 0 ]; then 
+if [ "$USERID" -ne 0 ]; then
     echo "Only root users can execute this script"
     exit 1
 fi
 
-validation(){
-    if [ $1 -ne 0 ]; then 
-        echo "$2 is failed"
-        exit 1
-    else 
-        echo "$2 is completed"
-    fi
-}
-
-checksoft(){
-    if dnf list installed $1 &> /dev/null; then 
-        echo "$1 already installed"
+validation() {
+    if [ "$1" -ne 0 ]; then
+        echo "$2 FAILED"
         exit 1
     else
-        echo "Installing $1"
-        dnf install $1 -y
+        echo "$2 COMPLETED"
     fi
 }
 
-checksoft nginx
+install_if_missing() {
+    local pkg="$1"
+
+    if dnf list installed "$pkg" &>/dev/null; then
+        echo "$pkg already installed"
+        return 0
+    else
+        echo "Installing $pkg"
+        dnf install "$pkg" -y
+        #return $?
+    fi
+}
+
+install_if_missing ngginx
 validation $? "nginx installation"
 
-checksoft mysql
-validation $? "mysql installation"
+# install_if_missing mysql
+# validation $? "mysql installation"
 
-checksoft nodejs
-validation $? "nodejs installation"
+# install_if_missing nodejs
+# validation $? "nodejs installation"
